trigger:
  branches:
    include:
      - main
      - develop
  paths:
    include:
    - src/**

variables:
  # Environment name
  - name: environment
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      value: 'prod'
    ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
      value: 'dev'
    ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      ${{ if ne(variables['Build.SourceBranchName'], 'develop') }}:
        value: 'dev'
  
  # Docker image variables
  - name: dockerRegistryServiceConnection
    value: 'acr-service-connection'
  - name: acrName
    value: 'aksstoredevacr'
  - name: acrLoginServer
    value: 'aksstoredevacr.azurecr.io'
  - name: imageRepository
    value: 'aks-store'
  - name: tag
    value: '$(Build.BuildId)'

stages:
# Stage 1: Build and Push Docker Images
- stage: Build
  displayName: 'Build and Push Docker Images'
  jobs:
  - job: BuildImages
    displayName: 'Build and Push Images'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Azure CLI Login'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name $(acrName)
    
    # Build and push store-front
    - task: Docker@2
      displayName: 'Build and Push store-front'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)/store-front'
        command: 'buildAndPush'
        Dockerfile: 'src/store-front/Dockerfile'
        buildContext: 'src/store-front'
        tags: |
          $(tag)
          latest
    
    # Build and push store-admin
    - task: Docker@2
      displayName: 'Build and Push store-admin'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)/store-admin'
        command: 'buildAndPush'
        Dockerfile: 'src/store-admin/Dockerfile'
        buildContext: 'src/store-admin'
        tags: |
          $(tag)
          latest
    
    # Build and push order-service
    - task: Docker@2
      displayName: 'Build and Push order-service'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)/order-service'
        command: 'buildAndPush'
        Dockerfile: 'src/order-service/Dockerfile'
        buildContext: 'src/order-service'
        tags: |
          $(tag)
          latest
    
    # Build and push product-service
    - task: Docker@2
      displayName: 'Build and Push product-service'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)/product-service'
        command: 'buildAndPush'
        Dockerfile: 'src/product-service/Dockerfile'
        buildContext: 'src/product-service'
        tags: |
          $(tag)
          latest
    
    # Build and push makeline-service
    - task: Docker@2
      displayName: 'Build and Push makeline-service'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)/makeline-service'
        command: 'buildAndPush'
        Dockerfile: 'src/makeline-service/Dockerfile'
        buildContext: 'src/makeline-service'
        tags: |
          $(tag)
          latest
    
    # Build and push ai-service if it exists
    - task: Docker@2
      displayName: 'Build and Push ai-service'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)/ai-service'
        command: 'buildAndPush'
        Dockerfile: 'src/ai-service/Dockerfile'
        buildContext: 'src/ai-service'
        tags: |
          $(tag)
          latest
      continueOnError: true

# Stage 2: Run Tests
- stage: Test
  displayName: 'Run Tests'
  dependsOn: Build
  jobs:
  - job: RunTests
    displayName: 'Run Unit Tests'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "Running frontend tests"
        # Add commands to run frontend tests here
        # e.g., cd src/store-front && npm ci && npm test
      displayName: 'Run Frontend Tests'
      
    - script: |
        echo "Running backend tests"
        # Add commands to run backend tests here
        # e.g., cd src/order-service && npm ci && npm test
      displayName: 'Run Backend Tests'
